## Install Numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
pip install --upgrade pip

  Using cached pip-25.2-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-25.2-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 25.1.1
    Uninstalling pip-25.1.1:
      Successfully uninstalled pip-25.1.1
Note: you may need to restart the kernel to use updated packages.


## Importing Numpy

In [1]:
import numpy as np

## Creating Numpy Arrays

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## Types of Arrays

**One-Dimensional (1D) Array**

In [4]:
arr1D = np.array([10, 20, 30, 40]) 
print(arr1D)

[10 20 30 40]


**Two-Dimensional (2D) Array (Matrix)**

In [5]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2D)

[[1 2 3]
 [4 5 6]]


**Three-Dimensional (3D) Array (Tensor)**

In [6]:
arr3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) 
print(arr3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Checking Numpy Version

In [7]:
print(np.__version__)

2.3.2


## Comparing Execution Time

In [3]:
import time 
# Using Python List 
lst = list(range(1000000)) 
start = time.time() 
lst = [x*2 for x in lst] 
end = time.time() 
print("Python List Time:", end - start) 
# Using NumPy Array 
arr = np.arange(1000000) 
start = time.time() 
arr = arr * 2 
end = time.time() 
print("NumPy Array Time:", end - start)

Python List Time: 0.04584479331970215
NumPy Array Time: 0.0017659664154052734


## Basic Array Attributes

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr.ndim) # Output: 2 (2D array) 
print(arr.shape) # Output: (2, 3) → 2 rows, 3 columns 
print(arr.size) # Output: 6 (total elements) 
print(arr.dtype) # Output: int64 (data type) 
print(arr.itemsize) # Output: 4 (bytes per element)

2
(2, 3)
6
int64
8


## Indexing

In [9]:
arr = np.array([10, 20, 30, 40, 50]) 
print(arr[0]) # Output: 10 
print(arr[2]) # Output: 30 
print(arr[-1]) # Output: 50 (Last element)

10
30
50


## Slicing

In [11]:
arr = np.array([10, 20, 30, 40, 50, 60, 70]) 
print(arr[1:5]) # Output: [20 30 40 50]
print(arr[:4]) # Output: [10 20 30 40] (First 4 elements) 
print(arr[2:]) # Output: [30 40 50 60 70] (From index 2 to end) 
print(arr[::2]) # Output: [10 30 50 70] (Every 2nd element) 
print(arr[::-1]) # Output: [70 60 50 40 30 20 10] (Reversed)

[20 30 40 50]
[10 20 30 40]
[30 40 50 60 70]
[10 30 50 70]
[70 60 50 40 30 20 10]


In [12]:
pip install nbconvert



   ------------- --------------------------  7/21 [mistune]
   -------------------- ------------------- 11/21 [bleach]
   -------------------------- ------------- 14/21 [jinja2]
   ---------------------------- ----------- 15/21 [beautifulsoup4]
   ---------------------------------- ----- 18/21 [nbformat]
   ---------------------------------------- 21/21 [nbconvert]

Note: you may need to restart the kernel to use updated packages.
